version: '3.2'
services:
  tmodloader:
    image: radioactivehydra/tmodloader:latest
    container_name: tmodloader
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 7777:7777
    volumes:
      - type: bind
        source: ./Worlds
        target: /tmodserver/.local/share/Terraria/tModLoader/Worlds/
      - type: bind
        source: ./Mods
        target: /tmodserver/.local/share/Terraria/tModLoader/Mods/
      - type: bind
        source: ./ModConfigs
        target: /tmodserver/.local/share/Terraria/tModLoader/ModConfigs/
      - type: bind
        source: ./serverconfig.txt
        target: /tmodserver/serverconfig.txt
        read_only: true
